#!/bin/bash

echo "Copying config files..."
cd /tmp/rice
cp -R . ~/
cd ~/

echo "Removing junk files..."
rm -rf ~/hexpkg.json
rm -rf ~/index.js
rm -rf ~/LICENSE
rm -rf ~/README.md
rm -rf ~/.git
rm -rf ~/.config/nvim/plugged 

echo "Setting up config files..."
rm -rf ~/Wallpaper.png 

ln -s ~/background_1080.png ~/Wallpaper.png
chmod +x ~/.config/bspwm/bspwmrc 
chmod +x ~/.config/polybar/launch.sh
chmod +x ~/.config/sxhkd/sxhkdrc

echo "Please enter your password for changing shells:"

chsh -s /usr/bin/zsh
sh -c "$(curl -fsSL https://starship.rs/install.sh)"

echo "Installing PARU aur helper..."
# make sure we have base-devel
sudo pacman --noconfirm -S --needed base-devel
git clone https://aur.archlinux.org/paru.git /tmp/paru
cd /tmp/paru
makepkg -si --noconfirm

echo "Installing dependencies..."
paru -Sy --noconfirm $DEPS # deps is defined by the installer, it is not broken.

python -m pip install neovim

echo ":PlugInstall" > /tmp/install_nvim_config

vim -s /tmp/install_nvim_config
echo "Installed!"
